---
- name: create oo_hosts_containerized_managed_true host group
  hosts: oo_all_hosts:!oo_nodes_to_config
  tasks:
  - group_by:
      key: oo_hosts_containerized_managed_{{ (containerized | default(False)) | ternary('true','false') }}
