---
- import_playbook: build_container_groups.yml

- hosts: oo_nodes_to_config:oo_hosts_containerized_managed_true
  roles:
    - role: container_runtime
  tasks:
    - import_role:
        name: container_runtime
        tasks_from: package_docker.yml
      when:
        - not openshift_docker_use_system_container | bool
        - not openshift_use_crio_only | bool
    - import_role:
        name: container_runtime
        tasks_from: systemcontainer_docker.yml
      when:
        - openshift_docker_use_system_container | bool
        - not openshift_use_crio_only | bool
    - import_role:
        name: container_runtime
        tasks_from: systemcontainer_crio.yml
      when:
        - openshift_use_crio | bool
        - openshift_docker_is_node_or_master | bool
